# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataType', models.CharField(max_length=42)),
                ('dataFile', models.FileField(upload_to=b'')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('labelConfidenceVals', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='datasample',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SherlockServer.Location'),
        ),
    ]
