# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SherlockServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureType', models.CharField(max_length=42)),
                ('featureFile', models.FileField(upload_to=b'')),
                ('dataSample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SherlockServer.DataSample')),
            ],
        ),
    ]
