# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SherlockServer', '0002_datafeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafeature',
            name='featureFile',
            field=models.FilePathField(path=b'/Users/Ahmed/Downloads/QSIURP2016/code_anurag/sherlock_server/SherlockServer/features/'),
        ),
    ]
