# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SherlockServer', '0003_auto_20170417_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafeature',
            name='classificationResult',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
