# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SherlockServer', '0004_datafeature_classificationresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafeature',
            name='classificationResult',
            field=models.TextField(null=True),
        ),
    ]
