"""
Django settings for sherlock_server project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.join(BASE_DIR, 'SherlockServer')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'kmiy_urf$944b#3b2fm&c4t@w1lpd=iujycw+t110(%(z1tuj^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.27.9.25',
                 '0.0.0.0',
                 '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'SherlockServer',
    'django_crontab'
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(PROJECT_ROOT,'debug.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django_crontab.crontab': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        '': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

CRONJOBS = [
    ('*/1 * * * *', 'SherlockServer.cron.extractFeatures', '>> ~/cronjob.log'),
    ('*/1 * * * *', 'SherlockServer.cron.classify', '>> ~/cronjob.log'),
    ('*/1 * * * *', 'SherlockServer.cron.updateConfidence', '>> ~/cronjob.log'),
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sherlock_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(PROJECT_ROOT,'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sherlock_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_ROOT = os.path.join(PROJECT_ROOT,'static/')
if not os.path.exists(STATIC_ROOT):
    os.mkdir(STATIC_ROOT)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(PROJECT_ROOT,'media/')
if not os.path.exists(MEDIA_ROOT):
    os.mkdir(MEDIA_ROOT)
STATIC_URL = '/static/'
FEAT_ROOT = os.path.join(PROJECT_ROOT,'features/')
if not os.path.exists(FEAT_ROOT):
    os.mkdir(FEAT_ROOT)
GMM_ROOT = os.path.join(PROJECT_ROOT, 'DataModels/GMMs/')
if not os.path.exists(GMM_ROOT):
    os.mkdir(GMM_ROOT)
VOCAB_ROOT = os.path.join(PROJECT_ROOT, 'DataModels/Vocab/')
if not os.path.exists(VOCAB_ROOT):
    os.mkdir(VOCAB_ROOT)
IMAGE_SVM_ROOT = os.path.join(PROJECT_ROOT, 'DataModels/ImageSVMs/')
if not os.path.exists(IMAGE_SVM_ROOT):
    os.mkdir(IMAGE_SVM_ROOT)